baseURL = "http://powergears.github.io/"
languageCode = "en-us"
title = "Bens Blog"
theme = "ananke"
pygmentsCodeFences = true

[params]
  favicon = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/spiderman-image.webp"
  recent_posts_number = 5
