image: seetheprogress/hugo:v0.30.2-51c2ee

build pages:about for demo:
  stage: build
  environment: development
  only:
    - master
  script:
  - apk --no-cache add nodejs-npm
  - npm install netlify-cli -g
  - cd exampleSite
  - find . -name 'config.toml' -type f -exec sed -i -e 's/stats.example.com/stats.seetheprogress.eu/g' -- {} +
  - find . -name 'config.toml' -type f -exec sed -i -e 's/www.example.com/syna-demo.netlify.com/g' -- {} +
  - find . -name 'config.toml' -type f -exec sed -i -e 's/id = "42"/id = "13"/g' -- {} +
  - /hugo
  - netlify deploy -p public -s $SITE -t $TOKEN
