name = "Syna"
license = "Apache License 2.0"
licenselink = "https://github.com/okkur/syna/blob/master/LICENSE"
description = "A customizable one to multi page theme for open source projects, companies and freelancers."
homepage = "https://github.com/okkur/syna"
tags = ["open source", "company", "one-page", "multi-page"]
min_version = 0.40

[author]
  name = "okkur"
  homepage = "https://github.com/okkur"

# Based on work from David Miller with his startbootstrap-agency theme and the hugo port from digitalcraftsman.
